name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Unix
      run: go build -v -o out/

    - name: Build Windows
      run: env GOOS=windows go build -v -o out/
      
    - name: Version
      run: echo "::set-output name=version::${GITHUB_REF_NAME:1}"

    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: "out/*"